---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tomcat
        image: ACR.azurecr.io/example-tomcat
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tomcat
