---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: springboot
        image: ACR_NAME.azurecr.io/example-springboot
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: springboot
