on: 
  push:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
name: group/create
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        export RESOURCE_GROUP=azure-examples
        export REGION=westus2
        export RESOURCE_GROUP=azure-examples-$RANDOM
        az group create --name $RESOURCE_GROUP --location $REGION
        export RESULT=$(az group show --name $RESOURCE_GROUP --output tsv --query properties.provisioningState)
        az group delete --name $RESOURCE_GROUP --yes || true
        if [[ "$RESULT" != Succeeded ]]; then
          exit 1
        fi
