on: 
  workflow_dispatch: 

name: 'aci/quarkus/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          mvn package
          mvn quarkus:dev
          export ACR_QUARKUS_IMAGE=acr-quarkus:latest
          
          az acr build --registry $ACR --image $ACR_QUARKUS_IMAGE .
          export ACI_QUARKUS=aci-quarkus-$RANDOM
          
          az container create \
          --resource-group $RESOURCE_GROUP \
          --name $ACI_QUARKUS \
          --image $ACR.azurecr.io/acr-quarkus:latest \
          --registry-login-server $ACR.azurecr.io \
          --registry-username $ACR_PULL_SERVICE_PRINCIPAL_ID \
          --registry-password $ACR_PULL_SERVICE_PRINCIPAL_PASSWORD \
          --dns-name-label $ACI_QUARKUS_NAME \
          --ports 8080
          
          echo `az container show \
          --resource-group $RESOURCE_GROUP \
          --name $ACI_QUARKUS \
          --query ipAddress.fqdn \
          --output tsv`:8080