on: 
  schedule: 
    - cron: '0 1 * * 2'
  workflow_dispatch: 

name: 'acr/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $ACR ]]; then
          export ACR=acr$RANDOM
          fi
          az acr create \
          --name $ACR \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          export RESULT=$(az acr show --name $ACR --resource-group $RESOURCE_GROUP --output tsv --query properties.provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Azure Container Registry $ACR was not provisioned properly"
          exit 1
          fi