on: 
  workflow_dispatch: 

name: 'acr/quarkus/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          mvn package
          mvn quarkus:dev
          export ACR_QUARKUS_IMAGE=acr-quarkus:latest
          
          az acr build --registry $ACR_NAME --image $ACR_QUARKUS_IMAGE .