on: 
  workflow_dispatch: 

name: 'acr/create-access-keys-settings-xml/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: | 
          export ACR_USERNAME=`az acr credential show --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP --query username --output tsv`
          export ACR_PASSWORD=`az acr credential show --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP --query passwords[0].value --output tsv`
          export SETTINGS_XML=$PWD/settings.xml