on: 
  workflow_dispatch: 

name: 'acr/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'azure/checkout@v2'
      - run: | 
          export ACR_NAME=acr$RANDOM
          
          az acr create \
          --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true