on: 
  schedule: 
    - cron: '0 2 * * 2'
  workflow_dispatch: 

name: 'acr/create-settings-xml/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=azure-examples-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $ACR ]]; then
          export ACR=acr$RANDOM
          fi
          az acr create \
          --name $ACR \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          export ACR_USERNAME=`az acr credential show --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP --query username --output tsv`
          export ACR_PASSWORD=`az acr credential show --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP --query passwords[0].value --output tsv`
          export SETTINGS_XML=$PWD/settings.xml
          az group delete --name $RESOURCE_GROUP --yes || true
          
          if [[ -z $ACR_USERNAME ]]; then
          echo "ACR Admin username was not found"
          exit 1
          fi
          
          if [[ -z $ACR_PASSWORD" ]]; then
          echo "ACR Admin passsword was not found"
          exit 1
          fi