on: 
  workflow_dispatch: 

name: 'acr/tomcat/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          mvn package
          export ACR_TOMCAT_IMAGE=acr-tomcat:latest
          
          az acr build --registry $ACR_NAME --image $ACR_TOMCAT_IMAGE .