on: 
  workflow_dispatch: 

name: 'aks/wildfly/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: | 
          sed -i "" "s/ACR/$ACR_NAME/g" deployment.yml
          kubectl apply -f deployment.yml