on: 
  workflow_dispatch: 

name: 'aks/create-kube-config/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS --admin --file config
          export KUBECONFIG=$PWD/config