on: 
  workflow_dispatch: 

name: 'appservice/docker-payara/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=azure-examples-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export APPSERVICE_PLAN=appservice-plan-$RANDOM
          
          az appservice plan create \
          --resource-group $RESOURCE_GROUP \
          --location westus2 \
          --name $APPSERVICE_PLAN \
          --is-linux \
          --sku P1V2