on: 
  workflow_dispatch: 

name: 'appservice/docker-jetty/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          export APPSERVICE_DOCKER_JETTY=appservice-docker-jetty-$RANDOM
          
          mvn azure-webapp:deploy \
          --settings=$SETTINGS_XML \
          -DappName=$APPSERVICE_DOCKER_JETTY \
          -DimageName=acr-jetty:latest \
          -DappServicePlan=$APPSERVICE_PLAN \
          -DresourceGroup=$RESOURCE_GROUP \
          -DserverId=$ACR
          
          az webapp show \
          --resource-group $RESOURCE_GROUP \
          --name $APPSERVICE_DOCKER_JETTY \
          --query hostNames[0] \
          --output tsv