on: 
  workflow_dispatch: 

name: 'appservice/delete-webapp/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          export RESOURCE_GROUP=azure-examples
          export REGION=westus2
          export RESOURCE_GROUP=azure-examples-$RANDOM
          az group create --name $RESOURCE_GROUP --location $REGION
          export APPSERVICE_PLAN=appservice-plan-$RANDOM
          
          az appservice plan create \
          --resource-group $RESOURCE_GROUP \
          --location westus2 \
          --name $APPSERVICE_PLAN \
          --is-linux \
          --sku P1V2
          
          cd appservice/tomcat-helloworld
          
          mvn clean install
          export APPSERVICE_TOMCAT_HELLOWORLD=helloworld-$RANDOM
          
          mvn azure-webapp:deploy \
          -DappName=$APPSERVICE_TOMCAT_HELLOWORLD \
          -DappServicePlan=$APPSERVICE_PLAN \
          -DresourceGroup=$RESOURCE_GROUP
          
          cd ../..
          
          az webapp delete --resource-group $RESOURCE_GROUP --name $APPSERVICE_TOMCAT_HELLOWORLD
          
          export RESULT=$(az webapp show --resource-group $RESOURCE_GROUP --name $APPSERVICE_TOMCAT_HELLOWORLD --output tsv --query state)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" == Running ]]; then
          exit 1
          fi