on: 
  workflow_dispatch: 

name: 'cosmosdb/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'azure/checkout@v2'
      - run: | 
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP