on: 
  schedule: 
    - cron: '0 3 * * 5'
  workflow_dispatch: 

name: 'eventhubs/create-authorization-rule/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          export EVENT_HUB_AUTHORIZATION_RULE=event-hub-auth-rule-$RANDOM
          az eventhubs eventhub authorization-rule create \
          --resource-group $RESOURCE_GROUP \
          --name $EVENT_HUB_AUTHORIZATION_RULE \
          --eventhub-name $EVENT_HUB \
          --namespace-name $EVENT_HUB_NAMESPACE \
          --rights Listen Send
          
          export RESULT=$(az eventhubs eventhub authorization-rule show --resource-group $RESOURCE_GROUP --namespace-name $EVENT_HUB_NAMESPACE --eventhub-name $EVENT_HUB --name $EVENT_HUB_AUTHORIZATION_RULE --query name --output tsv)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != "$EVENT_HUB_AUTHORIZATION_RULE" ]]; then
          exit 1
          fi