on: 
  schedule: 
    - cron: '0 * * * *'
  workflow_dispatch: 
name: hourly
jobs: 
  cleanup: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: | 
          export RESOURCE_GROUPS=$(az group list --query [*].name --output tsv)
          IFS='\n'
          for RESOURCE_GROUP in "$RESOURCE_GROUPS";
          do
            echo "Processing" $RESOURCE_GROUP
            if [[ "$RESOURCE_GROUP" == "azure-examples-*" ]]; then
              echo "Evaluating DeleteAfter for" $RESOURCE_GROUP
              export DELETE_AFTER=$(az group show --name $RESOURCE_GROUP --query tags.DeleteAfter)
              if [[ ((`date +%s` > $DELETE_AFTER )) ]]; then
                az group delete --name $RESOURCE_GROUP --yes
              else
                echo "Resource group show not be deleted yet"
              fi
            else
              echo "Skipping" $RESOURCE_GROUP
            fi
          done
          