on: 
  workflow_dispatch: 

name: 'keyvault/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: | 
          KEYVAULT_NAME="keyvault-$RANDOM"
          
          az keyvault create \
          --resource-group $RESOURCE_GROUP \
          --name $KEYVAULT_NAME