on: 
  workflow_dispatch: 

name: 'keyvault/add-secret/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: | 
          az keyvault secret set \
          --name mySecret \
          --value mySecretValue \
          --vault-name $KEYVAULT_NAME