on: 
  schedule: 
    - cron: '0 1 * * 2'
  workflow_dispatch: 

name: 'monitor/create-app-insights/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=azure-examples-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          az extension add -n application-insights
          if [[ -z $APP_INSIGHTS ]]; then
          export APP_INSIGHTS=app-insights-$RANDOM
          fi
          az monitor app-insights component create \
          --app $APP_INSIGHTS \
          --location $REGION \
          --resource-group $RESOURCE_GROUP
          
          export RESULT=$(az monitor app-insights component show --app $APP_INSIGHTS --resource-group $RESOURCE_GROUP --output tsv --query provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Application Insights $APP_INSIGHTS was not provisioned properly"
          exit 1
          fi