on: 
  workflow_dispatch: 

name: 'mysql/open-firewall-to-your-ip/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          export LOCAL_IP=`curl -s whatismyip.akamai.com`
          
          az mysql server firewall-rule create \
          --resource-group $RESOURCE_GROUP \
          --server $MYSQL_NAME \
          --name AllowMyLocalIP \
          --start-ip-address $LOCAL_IP \
          --end-ip-address $LOCAL_IP