on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
name: nightly
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_PASSWORD }}
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean install
    - name: Run GitHub Workflow Generator
      run: |
        rm -rf .github/workflows/*_md.yml
        cd tools/gwg/target
        java -jar gwg.jar --baseDirectory ../../.. --outputDirectory ../../../.github/workflows
        cd ../../..
        git config --global user.email "noreply@manorrock.com"
        git config --global user.name "Automated workflow"
        git add .
        git commit -a -m "Committing workflows" || true
        git push
        