on: 
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
name: nightly
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean install
    - name: Run GitHub Workflow Generator
      run: |
        rm -rf .github/workflows/*_md.yml
        cd tools/gwg/target
        java -jar gwg.jar --baseDirectory ../../.. --outputDirectory ../../../.github/workflows
        git status