on: 
  workflow_dispatch: 

name: 'spring-cloud/config-server/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: | 
          az spring-cloud config-server set \
          --config-file application.yml \
          --name ${SPRING_CLOUD_NAME} \
          --resource-group ${RESOURCE_GROUP}