on: 
  workflow_dispatch: 

name: 'webapp/create-a-deployment-slot/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'azure/checkout@v2'
      - run: | 
          az webapp deployment slot create \
          --resource-group $RESOURCE_GROUP \
          --name $TOMCAT_HELLOWORLD_WEBAPP \
          --slot staging